### ISSUE TITLE
GIT PUSH ERROR

### ISSUE THREAD

**Issue by ashapallan** [lgreski/datasciencectacontent#11]
fatal: An error occurred while sending the request.
fatal: The request was aborted: Could not create SSL/TLS secure channel.
remote: Support for password authentication was removed on August 13, 2021. Please use a personal access token instead.
remote: Please see https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information.
fatal: Authentication failed for 'https://github.com/ashapallan/datasciencecoursera/'

**Comment by lgreski** [comment]
The authentication error is for a different repository than datasciencectacontent. CLOSED.
