### ISSUE TITLE
Suggestion: Required accuracy calculation

### ISSUE THREAD

**Issue by mauriciocramos** [lgreski/datasciencectacontent#7]
You may want to include the required accuracy calculation as:

multiple_test_confidence_level ^ (1 / number_tests):

`> 0.95^(1/20)`
`[1] 0.9974386`

**Comment by lgreski** [comment]
Hello Mauricio. Would you please provide some additional context? Are you suggesting that I use the Šidák correction for multiple comparisons to establish the family wise error rate, and convert it to the required accuracy?

**Comment by mauriciocramos** [comment]
Dear Leonard, I'm sorry for the delay.
I based my suggestion just on your very nice advices.  Sometimes I feel like the course wouldn't be that good without them. :-)
It says the bottom line is to achieve at least .99 accuracy before do the 20 tests.
It means the model accuracy of .9900 estimates correctly predicting .85 of the 20 tests, which is 17 out of 20.
I wonder why 17 would be enough.  Who wouldn't want to (at least try) to get closer to 100%? ;-)
Not being that "ambitious", I used the typical error type I (alpha) as reference.
What would be the required model accuracy to reach the (1-alpha) probability for the 20 tests? a = (1-.05)^(1/20)
I'm not very academic, but digging what you asked about Šidák's it seems you are right.  I'm sorry not to have much time explore this reference for now.
By the way, in my report I wrote: "The required model accuracy to correctly predict all 20 tests with 95% confidence is 0.9974. The estimated model accuracy is 0.9929..."
I achieved this with seed 1/random forest/cross-validation 10 times/mtry 10/ntree 500.
Please let me know any mistake.
Thank you.

**Comment by lgreski** [comment]
Thanks for the confirmation, Mauricio. If you compare the approach I used (i.e. Bayes Theorem) with the Šidák correction for multiple tests, you'll find that they produce the same result within 0.001. 

```
> mdlAccuracy <- c(.8,.85,.9,.95,.99,.995,.996,.997,.9974,0.9974386,.9975)
> predAccuracy <- mdlAccuracy^20
> data.frame(mdlAccuracy,predAccuracy)
   mdlAccuracy predAccuracy
1    0.8000000   0.01152922
2    0.8500000   0.03875953
3    0.9000000   0.12157665
4    0.9500000   0.35848592
5    0.9900000   0.81790694
6    0.9950000   0.90461048
7    0.9960000   0.92296826
8    0.9970000   0.94167961
9    0.9974000   0.94926458
10   0.9974386   0.94999960
11   0.9975000   0.95116988
> 
> # alternate approach: Šidák's correction of multiple tests
> # generate 95% confidence for 20 tests
> (1 - .05)^(1/20)
[1] 0.9974386
>
```

regards,

Len

**Comment by mauriciocramos** [comment]
That's it! Many thanks!
