### ISSUE TITLE
getting  length 0 and mode NULL

### ISSUE THREAD

**Issue by rupesh2017** [lgreski/datasciencectacontent#8]
![screenshot from 2018-04-03 17-23-57](https://user-images.githubusercontent.com/31857722/38386597-b815981c-3932-11e8-9548-f780e1f9dca1.png)

**Comment by lgreski** [comment]
Hello Rupesh. You have a typo in your `lapply()` function. The **Attack** column starts with a capital **A**, noting that R is case sensitive. 

regards,

Len
