### ISSUE TITLE
Error in R installation

### ISSUE THREAD

**Issue by vanya0304** [lgreski/datasciencectacontent#9]
Hello,
Thank you for the detailed instructions.
When I try installing R using this code, it is showing the following error:

Malformed entry 6 in the list file /etc/apt/sources.list (Component)
The list of sources could not be read.

When I run R, it opens the 3.2 version of R, which I think is the default version of R installed in my laptop.

Could you please help?

**Comment by lgreski** [comment]
Which code are you referring to in your post? Also, the current version of R is 3.6.2. The release you have on your laptop is very old.

**Comment by lgreski** [comment]
Unable to reproduce.
